---
- name: Enable internal repos
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: yes
    gpgcheck: no
  with_items:
    - name: crio
      description: CRI-O repo
      baseurl: https://cbs.centos.org/repos/paas7-crio-113-candidate/x86_64/os
    - name: hyperkube
      description: Hyperkube repo
      baseurl: https://rpms.svc.ci.openshift.org/openshift-origin-v4.1/

- name: Install remote runc
  dnf:
    name: 'https://rpmfind.net/linux/fedora/linux/updates/28/Everything/x86_64/Packages/r/runc-1.0.0-83.dev.gitf56b4cb.fc28.x86_64.rpm'
    state: present

- name: Install openshift support packages
  package:
    name: "{{ openshift_node_support_packages | join(',') }}"
    update_cache: true
  async: 3600
  poll: 30

- name: Install openshift packages
  package:
    name: "{{ openshift_node_packages | join(',') }}"
    state: "{{ openshift_node_package_state }}"
  async: 3600
  poll: 30

- name: Enable the CRI-O service
  systemd:
    name: "cri-o"
    enabled: yes
